language: go

go:
- 1.20

install:
- go get -v -t ./...
- go install github.com/mattn/goveralls@latest

script:
# Run query "unit tests".
- make
- go test -short -v ./... -cover=1 -coverprofile=_c.cov
- $GOPATH/bin/goveralls -service=travis-pro -coverprofile=_c.cov
